stages:
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_INCREMENTAL: "0"

default:
  image: rust:latest
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - .cargo/
      - target/

test:
  stage: test
  before_script:
    - rustc --version && cargo --version
    - |
      if ! command -v cargo-binstall &>/dev/null; then
        cargo install cargo-binstall --locked
      fi
    - cargo binstall cargo-nextest --secure -y
    - cargo binstall cargo-llvm-cov -y
  artifacts:
    reports:
      junit: target/nextest/default/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml
  coverage: '/TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/'
  script:
    - cargo llvm-cov nextest
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov-target/cobertura.xml
